# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/egk69/Documents/Development/EDAC_SDRAM_Controller/Xilinx/artix_sdram_demo/artix_sdram_demo.srcs/sources_1/bd/DemoSDRAM/ip/DemoSDRAM_mdm_1_0/DemoSDRAM_mdm_1_0.xci
# IP: The module: 'DemoSDRAM_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/egk69/Documents/Development/EDAC_SDRAM_Controller/Xilinx/artix_sdram_demo/artix_sdram_demo.srcs/sources_1/bd/DemoSDRAM/ip/DemoSDRAM_mdm_1_0/DemoSDRAM_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoSDRAM_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/egk69/Documents/Development/EDAC_SDRAM_Controller/Xilinx/artix_sdram_demo/artix_sdram_demo.srcs/sources_1/bd/DemoSDRAM/ip/DemoSDRAM_mdm_1_0/DemoSDRAM_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoSDRAM_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/egk69/Documents/Development/EDAC_SDRAM_Controller/Xilinx/artix_sdram_demo/artix_sdram_demo.srcs/sources_1/bd/DemoSDRAM/ip/DemoSDRAM_mdm_1_0/DemoSDRAM_mdm_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoSDRAM_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/egk69/Documents/Development/EDAC_SDRAM_Controller/Xilinx/artix_sdram_demo/artix_sdram_demo.srcs/sources_1/bd/DemoSDRAM/ip/DemoSDRAM_mdm_1_0/DemoSDRAM_mdm_1_0.xci
# IP: The module: 'DemoSDRAM_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/egk69/Documents/Development/EDAC_SDRAM_Controller/Xilinx/artix_sdram_demo/artix_sdram_demo.srcs/sources_1/bd/DemoSDRAM/ip/DemoSDRAM_mdm_1_0/DemoSDRAM_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoSDRAM_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/egk69/Documents/Development/EDAC_SDRAM_Controller/Xilinx/artix_sdram_demo/artix_sdram_demo.srcs/sources_1/bd/DemoSDRAM/ip/DemoSDRAM_mdm_1_0/DemoSDRAM_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoSDRAM_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/egk69/Documents/Development/EDAC_SDRAM_Controller/Xilinx/artix_sdram_demo/artix_sdram_demo.srcs/sources_1/bd/DemoSDRAM/ip/DemoSDRAM_mdm_1_0/DemoSDRAM_mdm_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoSDRAM_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
