// EDAC_SDRAM_Controller_Demo_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module EDAC_SDRAM_Controller_Demo_mm_interconnect_0 (
		input  wire        altpll_0_c1_clk,                                                              //                                                            altpll_0_c1.clk
		input  wire        spi_slave_to_avalon_mm_master_bridge_0_clk_reset_reset_bridge_in_reset_reset, // spi_slave_to_avalon_mm_master_bridge_0_clk_reset_reset_bridge_in_reset.reset
		input  wire [31:0] spi_slave_to_avalon_mm_master_bridge_0_avalon_master_address,                 //                   spi_slave_to_avalon_mm_master_bridge_0_avalon_master.address
		output wire        spi_slave_to_avalon_mm_master_bridge_0_avalon_master_waitrequest,             //                                                                       .waitrequest
		input  wire [3:0]  spi_slave_to_avalon_mm_master_bridge_0_avalon_master_byteenable,              //                                                                       .byteenable
		input  wire        spi_slave_to_avalon_mm_master_bridge_0_avalon_master_read,                    //                                                                       .read
		output wire [31:0] spi_slave_to_avalon_mm_master_bridge_0_avalon_master_readdata,                //                                                                       .readdata
		output wire        spi_slave_to_avalon_mm_master_bridge_0_avalon_master_readdatavalid,           //                                                                       .readdatavalid
		input  wire        spi_slave_to_avalon_mm_master_bridge_0_avalon_master_write,                   //                                                                       .write
		input  wire [31:0] spi_slave_to_avalon_mm_master_bridge_0_avalon_master_writedata,               //                                                                       .writedata
		output wire [24:0] edac_sdram_controller_0_portb_address,                                        //                                          edac_sdram_controller_0_portb.address
		output wire        edac_sdram_controller_0_portb_write,                                          //                                                                       .write
		output wire        edac_sdram_controller_0_portb_read,                                           //                                                                       .read
		input  wire [31:0] edac_sdram_controller_0_portb_readdata,                                       //                                                                       .readdata
		output wire [31:0] edac_sdram_controller_0_portb_writedata,                                      //                                                                       .writedata
		input  wire        edac_sdram_controller_0_portb_readdatavalid,                                  //                                                                       .readdatavalid
		input  wire        edac_sdram_controller_0_portb_waitrequest                                     //                                                                       .waitrequest
	);

	wire         spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_waitrequest;   // edac_sdram_controller_0_portb_translator:uav_waitrequest -> spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator:uav_waitrequest
	wire  [31:0] spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_readdata;      // edac_sdram_controller_0_portb_translator:uav_readdata -> spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator:uav_readdata
	wire         spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_debugaccess;   // spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator:uav_debugaccess -> edac_sdram_controller_0_portb_translator:uav_debugaccess
	wire  [31:0] spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_address;       // spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator:uav_address -> edac_sdram_controller_0_portb_translator:uav_address
	wire         spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_read;          // spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator:uav_read -> edac_sdram_controller_0_portb_translator:uav_read
	wire   [3:0] spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_byteenable;    // spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator:uav_byteenable -> edac_sdram_controller_0_portb_translator:uav_byteenable
	wire         spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_readdatavalid; // edac_sdram_controller_0_portb_translator:uav_readdatavalid -> spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator:uav_readdatavalid
	wire         spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_lock;          // spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator:uav_lock -> edac_sdram_controller_0_portb_translator:uav_lock
	wire         spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_write;         // spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator:uav_write -> edac_sdram_controller_0_portb_translator:uav_write
	wire  [31:0] spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_writedata;     // spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator:uav_writedata -> edac_sdram_controller_0_portb_translator:uav_writedata
	wire   [2:0] spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_burstcount;    // spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator:uav_burstcount -> edac_sdram_controller_0_portb_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator (
		.clk                    (altpll_0_c1_clk),                                                                                         //                       clk.clk
		.reset                  (spi_slave_to_avalon_mm_master_bridge_0_clk_reset_reset_bridge_in_reset_reset),                            //                     reset.reset
		.uav_address            (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_waitrequest),                                        //                          .waitrequest
		.av_byteenable          (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_byteenable),                                         //                          .byteenable
		.av_read                (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_read),                                               //                          .read
		.av_readdata            (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_readdatavalid),                                      //                          .readdatavalid
		.av_write               (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_write),                                              //                          .write
		.av_writedata           (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                                                    //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                                                    //               (terminated)
		.av_begintransfer       (1'b0),                                                                                                    //               (terminated)
		.av_chipselect          (1'b0),                                                                                                    //               (terminated)
		.av_lock                (1'b0),                                                                                                    //               (terminated)
		.av_debugaccess         (1'b0),                                                                                                    //               (terminated)
		.uav_clken              (),                                                                                                        //               (terminated)
		.av_clken               (1'b1),                                                                                                    //               (terminated)
		.uav_response           (2'b00),                                                                                                   //               (terminated)
		.av_response            (),                                                                                                        //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                                                    //               (terminated)
		.av_writeresponsevalid  ()                                                                                                         //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (25),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) edac_sdram_controller_0_portb_translator (
		.clk                    (altpll_0_c1_clk),                                                                                         //                      clk.clk
		.reset                  (spi_slave_to_avalon_mm_master_bridge_0_clk_reset_reset_bridge_in_reset_reset),                            //                    reset.reset
		.uav_address            (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (spi_slave_to_avalon_mm_master_bridge_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (edac_sdram_controller_0_portb_address),                                                                   //      avalon_anti_slave_0.address
		.av_write               (edac_sdram_controller_0_portb_write),                                                                     //                         .write
		.av_read                (edac_sdram_controller_0_portb_read),                                                                      //                         .read
		.av_readdata            (edac_sdram_controller_0_portb_readdata),                                                                  //                         .readdata
		.av_writedata           (edac_sdram_controller_0_portb_writedata),                                                                 //                         .writedata
		.av_readdatavalid       (edac_sdram_controller_0_portb_readdatavalid),                                                             //                         .readdatavalid
		.av_waitrequest         (edac_sdram_controller_0_portb_waitrequest),                                                               //                         .waitrequest
		.av_begintransfer       (),                                                                                                        //              (terminated)
		.av_beginbursttransfer  (),                                                                                                        //              (terminated)
		.av_burstcount          (),                                                                                                        //              (terminated)
		.av_byteenable          (),                                                                                                        //              (terminated)
		.av_writebyteenable     (),                                                                                                        //              (terminated)
		.av_lock                (),                                                                                                        //              (terminated)
		.av_chipselect          (),                                                                                                        //              (terminated)
		.av_clken               (),                                                                                                        //              (terminated)
		.uav_clken              (1'b0),                                                                                                    //              (terminated)
		.av_debugaccess         (),                                                                                                        //              (terminated)
		.av_outputenable        (),                                                                                                        //              (terminated)
		.uav_response           (),                                                                                                        //              (terminated)
		.av_response            (2'b00),                                                                                                   //              (terminated)
		.uav_writeresponsevalid (),                                                                                                        //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                                                     //              (terminated)
	);

endmodule
