
####################################################################################
# Generated by Vivado 2016.4 built on 'Mon Jan 23 19:11:23 MST 2017' by 'xbuild'
# Command Used: write_xdc -force D:/Development/SEUD-MIST/SEUD/4_SDRTMRController/artix_sdram_demo/constrs_simple.xdc
####################################################################################


####################################################################################
# Constraints from file : 'DemoSDRAM_clk_wiz_1_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'DemoSDRAM_rst_clk_wiz_1_100M_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------





####################################################################################
# Constraints from file : 'DemoSDRAM_microblaze_0_0.xdc'
####################################################################################

current_instance DemoSDRAM_i/microblaze_0/U0
set_false_path -through [get_ports -scoped_to_current_instance Reset]
current_instance -quiet
current_instance DemoSDRAM_i/microblaze_0/U0
set_ip_msg_config -idlist {CDC-1 CDC-4 CDC-7 DPOP-3 PDCN-1569 REQP-1839 TIMING-10 TIMING-9}
current_instance -quiet


####################################################################################
# Constraints from file : 'DemoSDRAM_dlmb_v10_0.xdc'
####################################################################################

current_instance DemoSDRAM_i/microblaze_0_local_memory/dlmb_v10/U0
set_false_path -through [get_ports -scoped_to_current_instance SYS_Rst]


####################################################################################
# Constraints from file : 'DemoSDRAM_ilmb_v10_0.xdc'
####################################################################################

current_instance -quiet
current_instance DemoSDRAM_i/microblaze_0_local_memory/ilmb_v10/U0
set_false_path -through [get_ports -scoped_to_current_instance SYS_Rst]


####################################################################################
# Constraints from file : 'DemoSDRAM_mdm_1_0.xdc'
####################################################################################

# file: DemoSDRAM_mdm_1_0.xdc
# (c) Copyright 2013-2016 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.

current_instance -quiet
current_instance DemoSDRAM_i/mdm_1/U0
create_clock -period 33.333 [get_pins Use*.BSCAN*/*/DRCK]
create_clock -period 33.333 [get_pins Use*.BSCAN*/*/UPDATE]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins Use*.BSCAN*/*/DRCK]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins Use*.BSCAN*/*/UPDATE]]
set_false_path -through [get_pins Use*.BSCAN*/*/CAPTURE]
set_false_path -through [get_pins Use*.BSCAN*/*/SEL]
set_false_path -through [get_pins Use*.BSCAN*/*/SHIFT]
set_false_path -through [get_pins Use*.BSCAN*/*/TDI]
set_clock_groups -logically_exclusive -group [get_clocks -of_objects [get_pins Use*.BSCAN*/*/DRCK]] -group [get_clocks -of_objects [get_pins Use*.BSCAN*/*/UPDATE]]
current_instance -quiet
current_instance DemoSDRAM_i/mdm_1/U0
set_ip_msg_config -idlist {CDC-1 CDCM-1 REQP-1851 TIMING-10 TIMING-14 TIMING-2 TIMING-4 TIMING-9}
current_instance -quiet


####################################################################################
# Constraints from file : 'DemoSDRAM_clk_wiz_1_0.xdc'
####################################################################################


# file: DemoSDRAM_clk_wiz_1_0.xdc
#
# (c) Copyright 2008 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.
#

# Input clock periods. These duplicate the values entered for the
# input clocks. You can use these to time your system. If required
# commented constraints can be used in the top level xdc
#----------------------------------------------------------------
# Connect to input port when clock capable pin is selected for input
create_clock -period 83.332 [get_ports clk_shared]
set_input_jitter [get_clocks -of_objects [get_ports clk_shared]] 0.833


current_instance DemoSDRAM_i/clk_wiz_1/inst
set_property PHASESHIFT_MODE WAVEFORM [get_cells -hierarchical *adv*]


####################################################################################
# Constraints from file : 'DemoSDRAM_rst_clk_wiz_1_100M_0.xdc'
####################################################################################


# file: DemoSDRAM_rst_clk_wiz_1_100M_0.xdc
# (c) Copyright 2009 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.

current_instance -quiet
current_instance DemoSDRAM_i/rst_clk_wiz_1/U0
set_false_path -to [get_pins -hier *cdc_to*/D]


####################################################################################
# Constraints from file : 'DemoSDRAM_axi_amm_bridge_0_0.xdc'
####################################################################################

# file: DemoSDRAM_axi_amm_bridge_0_0.xdc
# (c) Copyright 2009 - 2016 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.
###################################################






####################################################################################
# Constraints from file : 'seud_sdram_sys_timing_constraints.sdc'
####################################################################################

#**************************************************************
# Time Information
#**************************************************************

#set_time_format -unit ns -decimal_places 3

#**************************************************************
# Create Clock
#**************************************************************

#create_clock -name {clk_12} -period 83.333 -waveform { 0.000 0.500 } [get_ports {clk_shared}]

#**************************************************************
# Create Generated Clock
#**************************************************************

#create_generated_clock -name clk_uBlaze -source [get_pins DemoSDRAM_i/clk_wiz_1/inst/clk_blaze]  -multiply_by 50 -divide_by 12  [get_pins {DemoSDRAM_i/microblaze_0/inst/Clk DemoSDRAM_i/microblaze_0_local_memory/inst/LMB_Clk DemoSDRAM_i/axi_clock_converter_0/inst/s_axi_aclk DemoSDRAM_i/rst_clk_wiz_1/inst/slowest_sync_clk}]
#create_generated_clock -name clk_controller -source [get_pins DemoSDRAM_i/clk_wiz_1/inst/clk_ctrl] -multiply_by 50 -divide_by 6 [get_pins {DemoSDRAM_i/axi_amm_bridge_0/inst/s_axi_aclk DemoSDRAM_i/axi_clock_converter_0/inst/m_axi_aclk DemoSDRAM_i/sdram_ctrl_tmr_avalon_0/inst/csi_clock}]
#create_generated_clock -name clk_sdram -source [get_pins DemoSDRAM_i/clk_wiz_1/inst/clk_sdram] -multiply_by 50 -divide_by 6 -edge_shift -54.00 [get_ports sdram_clk]

####create_generated_clock -name {sdram_clk_pin} -source {sdram_pll_inst|altpll_component|auto_generated|pll1|clk[1]} -phase -72.00 -duty_cycle 50.00 [get_ports DRAM_CLK]

#**************************************************************
# Set Clock Uncertainty
#**************************************************************

#derive_clock_uncertainty;

#**************************************************************
# Set Input Delay
# tHZ3/2 + routing delay
# #tLZ + routing delay
#**************************************************************

current_instance -quiet
set_input_delay -clock [get_clocks *sdram*] -max 8.400 [get_ports -filter { NAME =~ "*dataQ_io[*]*"}]
set_input_delay -clock [get_clocks *sdram*] -min 3.000 [get_ports -filter { NAME =~ "*dataQ_io[*]*"}]

#**************************************************************
# Set Output Delay
#**************************************************************

set_output_delay -clock [get_clocks *sdram*] -max 1.500 [get_ports -filter { NAME =~ "*addr_o[*]*" || NAME =~ "*bank_o[*]*" || NAME =~ "*dqm_o[*]*" || NAME =~ "*dataQ_io[*]*" || NAME =~ "*cas_o*" || NAME =~ "*ras_o*" || NAME =~ "*we_o*" || NAME =~ "*cs_o*" || NAME =~ "*cke_o*"}]

set_output_delay -clock [get_clocks *sdram*] -min -0.800 [get_ports -filter { NAME =~ "*addr_o[*]*" || NAME =~ "*bank_o[*]*" || NAME =~ "*dqm_o[*]*" || NAME =~ "*dataQ_io[*]*" || NAME =~ "*cas_o*" || NAME =~ "*ras_o*" || NAME =~ "*we_o*" || NAME =~ "*cs_o*" || NAME =~ "*cke_o*"}]

#**************************************************************
# Set Multicycle Path
#**************************************************************

set_multicycle_path -setup -end -from [get_clocks *sdram*] -to [get_clocks *ctrl*] 2
#set_multicycle_path -from [get_clocks {clk_sdram_DemoSDRAM_clk_wiz_1_0_1] -to [get_clocks {clk_ctrl_DemoSDRAM_clk_wiz_1_0_1] -setup -end 2




####################################################################################
# Constraints from file : 'pin_assignment.xdc'
####################################################################################

set_property PACKAGE_PIN E6 [get_ports cas_o]
set_property PACKAGE_PIN D6 [get_ports cke_o]
set_property PACKAGE_PIN G4 [get_ports ras_o]
set_property PACKAGE_PIN G5 [get_ports {bank_o[0]}]
set_property PACKAGE_PIN F4 [get_ports {bank_o[1]}]
set_property PACKAGE_PIN F5 [get_ports {addr_o[3]}]
set_property PACKAGE_PIN E5 [get_ports {addr_o[0]}]
set_property PACKAGE_PIN D4 [get_ports we_o]
set_property PACKAGE_PIN B17 [get_ports sdram_clk]
set_property PACKAGE_PIN C17 [get_ports {addr_o[4]}]
set_property PACKAGE_PIN C4 [get_ports {dataQ_io[3]}]
set_property PACKAGE_PIN B5 [get_ports {dataQ_io[0]}]
set_property PACKAGE_PIN A5 [get_ports {dataQ_io[2]}]
set_property PACKAGE_PIN B4 [get_ports {dataQ_io[1]}]
set_property PACKAGE_PIN D3 [get_ports {addr_o[1]}]
set_property PACKAGE_PIN E3 [get_ports {addr_o[2]}]
set_property PACKAGE_PIN C2 [get_ports {dataQ_io[7]}]
set_property PACKAGE_PIN A3 [get_ports {dataQ_io[6]}]
set_property PACKAGE_PIN A2 [get_ports {dataQ_io[5]}]
set_property PACKAGE_PIN A4 [get_ports {dataQ_io[4]}]
set_property PACKAGE_PIN A22 [get_ports {dataQ_io[8]}]
set_property PACKAGE_PIN A20 [get_ports {dataQ_io[9]}]
set_property PACKAGE_PIN B21 [get_ports {dataQ_io[10]}]
set_property PACKAGE_PIN E16 [get_ports {addr_o[9]}]
set_property PACKAGE_PIN D16 [get_ports {dataQ_io[13]}]
set_property PACKAGE_PIN A17 [get_ports {dataQ_io[14]}]
set_property PACKAGE_PIN A18 [get_ports {dataQ_io[11]}]
set_property PACKAGE_PIN A19 [get_ports {dataQ_io[12]}]
set_property PACKAGE_PIN E17 [get_ports {addr_o[6]}]
set_property PACKAGE_PIN E18 [get_ports {dqm_o[1]}]
set_property PACKAGE_PIN C18 [get_ports {addr_o[12]}]
set_property PACKAGE_PIN D19 [get_ports {addr_o[8]}]
set_property PACKAGE_PIN C19 [get_ports {addr_o[7]}]
set_property PACKAGE_PIN B20 [get_ports {addr_o[5]}]
set_property PACKAGE_PIN C3 [get_ports {addr_o[10]}]
set_property PACKAGE_PIN B2 [get_ports {dqm_o[0]}]
set_property PACKAGE_PIN F15 [get_ports {dataQ_io[15]}]
set_property PACKAGE_PIN B19 [get_ports {addr_o[11]}]
set_property PACKAGE_PIN AE2 [get_ports err_detect_o]
set_property PACKAGE_PIN U22 [get_ports clk_shared]
set_property PACKAGE_PIN F3 [get_ports cs_o]
set_property PULLDOWN true [get_ports cas_o]
set_property PULLDOWN true [get_ports cs_o]
set_property PULLDOWN true [get_ports we_o]
set_property PULLDOWN true [get_ports ras_o]
set_property PULLDOWN true [get_ports reset]
set_property PULLDOWN true [get_ports {dataQ_io[0]}]
set_property PULLDOWN true [get_ports {dataQ_io[1]}]
set_property PULLDOWN true [get_ports {dataQ_io[2]}]
set_property PULLDOWN true [get_ports {dataQ_io[3]}]
set_property PULLDOWN true [get_ports {dataQ_io[4]}]
set_property PULLDOWN true [get_ports {dataQ_io[5]}]
set_property PULLDOWN true [get_ports {dataQ_io[6]}]
set_property PULLDOWN true [get_ports {dataQ_io[7]}]
set_property PULLDOWN true [get_ports {dataQ_io[8]}]
set_property PULLDOWN true [get_ports {dataQ_io[9]}]
set_property PULLDOWN true [get_ports {dataQ_io[10]}]
set_property PULLDOWN true [get_ports {dataQ_io[11]}]
set_property PULLDOWN true [get_ports {dataQ_io[12]}]
set_property PULLDOWN true [get_ports {dataQ_io[13]}]
set_property PULLDOWN true [get_ports {dataQ_io[14]}]
set_property PULLDOWN true [get_ports {dataQ_io[15]}]
set_property PULLDOWN true [get_ports {dqm_o[0]}]
set_property PULLDOWN true [get_ports {dqm_o[1]}]
set_property PULLDOWN true [get_ports err_detect_o]
set_property SLEW FAST [get_ports err_detect_o]
set_property PULLDOWN true [get_ports sdram_clk]
set_property PULLDOWN true [get_ports scrubbing_proc_run_o]
set_property PULLDOWN true [get_ports healing_proc_run_o]
set_property PULLDOWN true [get_ports cke_o]
set_property PULLDOWN true [get_ports {addr_o[0]}]
set_property PULLDOWN true [get_ports {addr_o[1]}]
set_property PULLDOWN true [get_ports {addr_o[2]}]
set_property PULLDOWN true [get_ports {addr_o[3]}]
set_property PULLDOWN true [get_ports {addr_o[4]}]
set_property PULLDOWN true [get_ports {addr_o[5]}]
set_property PULLDOWN true [get_ports {addr_o[6]}]
set_property PULLDOWN true [get_ports {addr_o[7]}]
set_property PULLDOWN true [get_ports {addr_o[8]}]
set_property PULLDOWN true [get_ports {addr_o[9]}]
set_property PULLDOWN true [get_ports {addr_o[10]}]
set_property PULLDOWN true [get_ports {addr_o[11]}]
set_property PULLDOWN true [get_ports {addr_o[12]}]
set_property PULLDOWN true [get_ports {bank_o[0]}]
set_property PULLDOWN true [get_ports {bank_o[1]}]
set_property PULLDOWN true [get_ports clk_shared]




####################################################################################
# Constraints from file : 'DemoSDRAM_axi_clock_converter_0_0_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_clock_converter Component "DemoSDRAM_axi_clock_converter_0_0"
###############################################################################################################
#
# This component is not configured to perform asynchronous clock-domain-crossing.
# No timing core-level constraints are needed.
# (Synchronous clock-domain-crossings, if any, remain covered by your system-level PERIOD constraints.)




# User Generated XDC timing constraints 

set_operating_conditions -process maximum

# User Generated miscellaneous constraints 

set_property LOAD 50 [get_ports cas_o]
set_property LOAD 50 [get_ports {dataQ_io[7]}]
set_property LOAD 50 [get_ports sdram_clk]
set_property LOAD 50 [get_ports {dataQ_io[5]}]
set_property LOAD 50 [get_ports {dataQ_io[0]}]
set_property LOAD 50 [get_ports we_o]
set_property LOAD 50 [get_ports {bank_o[1]}]
set_property LOAD 50 [get_ports {addr_o[5]}]
set_property LOAD 50 [get_ports {addr_o[3]}]
set_property LOAD 50 [get_ports {addr_o[12]}]
set_property LOAD 50 [get_ports err_detect_o]
set_property LOAD 50 [get_ports {dataQ_io[3]}]
set_property LOAD 50 [get_ports {addr_o[9]}]
set_property LOAD 50 [get_ports cs_o]
set_property LOAD 50 [get_ports {dataQ_io[11]}]
set_property LOAD 50 [get_ports {addr_o[4]}]
set_property LOAD 50 [get_ports {addr_o[1]}]
set_property LOAD 50 [get_ports {bank_o[0]}]
set_property LOAD 50 [get_ports scrubbing_proc_run_o]
set_property LOAD 50 [get_ports {addr_o[10]}]
set_property LOAD 50 [get_ports {dataQ_io[8]}]
set_property LOAD 50 [get_ports {dataQ_io[9]}]
set_property LOAD 50 [get_ports {dataQ_io[13]}]
set_property LOAD 50 [get_ports {addr_o[7]}]
set_property LOAD 50 [get_ports {dataQ_io[14]}]
set_property LOAD 50 [get_ports healing_proc_run_o]
set_property LOAD 50 [get_ports {dataQ_io[12]}]
set_property LOAD 50 [get_ports {addr_o[2]}]
set_property LOAD 50 [get_ports ras_o]
set_property LOAD 50 [get_ports {addr_o[6]}]
set_property LOAD 50 [get_ports {dataQ_io[6]}]
set_property LOAD 50 [get_ports {dqm_o[0]}]
set_property LOAD 50 [get_ports cke_o]
set_property LOAD 50 [get_ports {dataQ_io[4]}]
set_property LOAD 50 [get_ports {dataQ_io[2]}]
set_property LOAD 50 [get_ports {dataQ_io[1]}]
set_property LOAD 50 [get_ports {addr_o[0]}]
set_property LOAD 50 [get_ports {addr_o[11]}]
set_property LOAD 50 [get_ports {addr_o[8]}]
set_property LOAD 50 [get_ports {dataQ_io[10]}]
set_property LOAD 50 [get_ports {dataQ_io[15]}]
set_property LOAD 50 [get_ports {dqm_o[1]}]

# User Generated XDC timing constraints 

set_load 50.000 [all_outputs]
set_operating_conditions -ambient_temp 10.0
set_operating_conditions -airflow 0
set_operating_conditions -board_layers 4to7
set_operating_conditions -board small
set_operating_conditions -heatsink none
set_switching_activity -deassert_resets 
set_switching_activity -default_toggle_rate 33.333

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
