# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/4_SDRTMRController/SEUD_pin_constrs.xdc

# XDC: imports/4_SDRTMRController/SEUD_timing_constrs.xdc

# Block Designs: bd/DemoSDRAM/DemoSDRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM || ORIG_REF_NAME==DemoSDRAM}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_microblaze_0_0/DemoSDRAM_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_microblaze_0_0 || ORIG_REF_NAME==DemoSDRAM_microblaze_0_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_dlmb_v10_0/DemoSDRAM_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_dlmb_v10_0 || ORIG_REF_NAME==DemoSDRAM_dlmb_v10_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_ilmb_v10_0/DemoSDRAM_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_ilmb_v10_0 || ORIG_REF_NAME==DemoSDRAM_ilmb_v10_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_dlmb_bram_if_cntlr_0/DemoSDRAM_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==DemoSDRAM_dlmb_bram_if_cntlr_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_ilmb_bram_if_cntlr_0/DemoSDRAM_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==DemoSDRAM_ilmb_bram_if_cntlr_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_lmb_bram_0/DemoSDRAM_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_lmb_bram_0 || ORIG_REF_NAME==DemoSDRAM_lmb_bram_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_mdm_1_0/DemoSDRAM_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_mdm_1_0 || ORIG_REF_NAME==DemoSDRAM_mdm_1_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_clk_wiz_1_0/DemoSDRAM_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_clk_wiz_1_0 || ORIG_REF_NAME==DemoSDRAM_clk_wiz_1_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_rst_clk_wiz_1_100M_0/DemoSDRAM_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==DemoSDRAM_rst_clk_wiz_1_100M_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_axi_amm_bridge_0_0/DemoSDRAM_axi_amm_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_axi_amm_bridge_0_0 || ORIG_REF_NAME==DemoSDRAM_axi_amm_bridge_0_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_sdram_ctrl_tmr_avalon_0_0/DemoSDRAM_sdram_ctrl_tmr_avalon_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_sdram_ctrl_tmr_avalon_0_0 || ORIG_REF_NAME==DemoSDRAM_sdram_ctrl_tmr_avalon_0_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_xlconstant_0_2/DemoSDRAM_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_xlconstant_0_2 || ORIG_REF_NAME==DemoSDRAM_xlconstant_0_2}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_microblaze_0_axi_periph_0/DemoSDRAM_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_microblaze_0_axi_periph_0 || ORIG_REF_NAME==DemoSDRAM_microblaze_0_axi_periph_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_xbar_0/DemoSDRAM_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_xbar_0 || ORIG_REF_NAME==DemoSDRAM_xbar_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_ila_0_0/DemoSDRAM_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_ila_0_0 || ORIG_REF_NAME==DemoSDRAM_ila_0_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_axi_traffic_gen_0_0/DemoSDRAM_axi_traffic_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_axi_traffic_gen_0_0 || ORIG_REF_NAME==DemoSDRAM_axi_traffic_gen_0_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_axi_protocol_converter_0_0/DemoSDRAM_axi_protocol_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_axi_protocol_converter_0_0 || ORIG_REF_NAME==DemoSDRAM_axi_protocol_converter_0_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_axi_crossbar_0_0/DemoSDRAM_axi_crossbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_axi_crossbar_0_0 || ORIG_REF_NAME==DemoSDRAM_axi_crossbar_0_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_xlconstant_0_0/DemoSDRAM_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_xlconstant_0_0 || ORIG_REF_NAME==DemoSDRAM_xlconstant_0_0}]

# IP: bd/DemoSDRAM/ip/DemoSDRAM_s00_mmu_0/DemoSDRAM_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoSDRAM_s00_mmu_0 || ORIG_REF_NAME==DemoSDRAM_s00_mmu_0}]

# XDC: bd/DemoSDRAM/DemoSDRAM_ooc.xdc
