# TCL File Generated by Component Editor 10.0
# Wed May 18 17:08:17 EEST 2016
# DO NOT MODIFY


# +-----------------------------------
# | 
# | seud_sdram_ctrl_tmr_avalon "SEUD SDRAM Controller (TMR impl.) - KTH" v1.0
# | Eleftherios Kyriakakis - KTH 2016.05.18.17:08:17
# | SDR SDRAM Controller with TMR impl.
# | 
# | D:/OneDrive/KTH/SUED Project IL2229/Altera/sdram_ctrl_tmr_avalon_interface.vhd
# | 
# |    ./sdram_ctrl_tmr.vhd syn
# |    ./tmr_error_generator.vhd syn
# |    ./sdram_ctrl_tmr_top.vhd syn
# |    ./tmr_address_mask.vhd syn
# |    ./sdram_ctrl_tmr_avalon_interface.vhd syn
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module seud_sdram_ctrl_tmr_avalon
# | 
set_module_property DESCRIPTION "SDR SDRAM Controller with TMR impl."
set_module_property NAME seud_sdram_ctrl_tmr_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Memories and Memory Controllers/SDRAM"
set_module_property AUTHOR "Eleftherios Kyriakakis - KTH"
set_module_property DISPLAY_NAME "SEUD SDRAM Controller (TMR impl.) - KTH"
set_module_property TOP_LEVEL_HDL_FILE sdram_ctrl_tmr_avalon_interface.vhd
set_module_property TOP_LEVEL_HDL_MODULE sdram_ctrl_tmr_avalon_interface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL FALSE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file sdram_ctrl_tmr.vhd SYNTHESIS
add_file utils_pack.vhd SYNTHESIS
add_file tmr_voter.vhd SYNTHESIS
add_file tmr_error_generator.vhd SYNTHESIS
add_file sdram_ctrl_tmr_scrubber.vhd SYNTHESIS
add_file sdram_ctrl_tmr_healer.vhd SYNTHESIS
add_file sdram_ctrl_tmr_top.vhd SYNTHESIS
add_file sdram_ctrl_tmr_avalon_interface.vhd SYNTHESIS
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter DATA_WIDTH INTEGER 32 ""
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH DESCRIPTION ""
set_parameter_property DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter DQM_WIDTH INTEGER 4
set_parameter_property DQM_WIDTH DEFAULT_VALUE 4
set_parameter_property DQM_WIDTH DISPLAY_NAME DQM_WIDTH
set_parameter_property DQM_WIDTH TYPE INTEGER
set_parameter_property DQM_WIDTH UNITS None
set_parameter_property DQM_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DQM_WIDTH AFFECTS_GENERATION false
set_parameter_property DQM_WIDTH HDL_PARAMETER true
add_parameter ROW_WIDTH INTEGER 13
set_parameter_property ROW_WIDTH DEFAULT_VALUE 13
set_parameter_property ROW_WIDTH DISPLAY_NAME ROW_WIDTH
set_parameter_property ROW_WIDTH TYPE INTEGER
set_parameter_property ROW_WIDTH UNITS None
set_parameter_property ROW_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ROW_WIDTH AFFECTS_GENERATION false
set_parameter_property ROW_WIDTH HDL_PARAMETER true
add_parameter COLS_WIDTH INTEGER 10
set_parameter_property COLS_WIDTH DEFAULT_VALUE 10
set_parameter_property COLS_WIDTH DISPLAY_NAME COLS_WIDTH
set_parameter_property COLS_WIDTH TYPE INTEGER
set_parameter_property COLS_WIDTH UNITS None
set_parameter_property COLS_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property COLS_WIDTH AFFECTS_GENERATION false
set_parameter_property COLS_WIDTH HDL_PARAMETER true
add_parameter BANK_WIDTH INTEGER 2
set_parameter_property BANK_WIDTH DEFAULT_VALUE 2
set_parameter_property BANK_WIDTH DISPLAY_NAME BANK_WIDTH
set_parameter_property BANK_WIDTH TYPE INTEGER
set_parameter_property BANK_WIDTH UNITS None
set_parameter_property BANK_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BANK_WIDTH AFFECTS_GENERATION false
set_parameter_property BANK_WIDTH HDL_PARAMETER true
add_parameter NOP_BOOT_CYCLES INTEGER 10000
set_parameter_property NOP_BOOT_CYCLES DEFAULT_VALUE 10000
set_parameter_property NOP_BOOT_CYCLES DISPLAY_NAME NOP_BOOT_CYCLES
set_parameter_property NOP_BOOT_CYCLES TYPE INTEGER
set_parameter_property NOP_BOOT_CYCLES UNITS None
set_parameter_property NOP_BOOT_CYCLES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NOP_BOOT_CYCLES AFFECTS_GENERATION false
set_parameter_property NOP_BOOT_CYCLES HDL_PARAMETER true
add_parameter REF_PERIOD INTEGER 75 "Maximum refresh command every 7.8125 microseconds. Must be less than SCRUBBER_WAIT_CYCLES."
set_parameter_property REF_PERIOD DEFAULT_VALUE 390
set_parameter_property REF_PERIOD DISPLAY_NAME REF_PERIOD
set_parameter_property REF_PERIOD TYPE INTEGER
set_parameter_property REF_PERIOD UNITS None
set_parameter_property REF_PERIOD ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REF_PERIOD DESCRIPTION "Refresh command should be issued at a maximum of every 7.8125 microseconds. Must be less than SCRUBBER_WAIT_CYCLES."
set_parameter_property REF_PERIOD AFFECTS_GENERATION false
set_parameter_property REF_PERIOD HDL_PARAMETER true
add_parameter REF_COMMAND_COUNT INTEGER 8 "How many refresh commands should be issued during initialization"
set_parameter_property REF_COMMAND_COUNT DEFAULT_VALUE 8
set_parameter_property REF_COMMAND_COUNT DISPLAY_NAME REF_COMMAND_COUNT
set_parameter_property REF_COMMAND_COUNT TYPE INTEGER
set_parameter_property REF_COMMAND_COUNT UNITS None
set_parameter_property REF_COMMAND_COUNT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REF_COMMAND_COUNT DESCRIPTION "How many refresh commands should be issued during initialization"
set_parameter_property REF_COMMAND_COUNT AFFECTS_GENERATION false
set_parameter_property REF_COMMAND_COUNT HDL_PARAMETER true
add_parameter REF_COMMAND_PERIOD INTEGER 8 "tRC Command Period"
set_parameter_property REF_COMMAND_PERIOD DEFAULT_VALUE 8
set_parameter_property REF_COMMAND_PERIOD DISPLAY_NAME REF_COMMAND_PERIOD
set_parameter_property REF_COMMAND_PERIOD TYPE INTEGER
set_parameter_property REF_COMMAND_PERIOD UNITS None
set_parameter_property REF_COMMAND_PERIOD ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REF_COMMAND_PERIOD DESCRIPTION "tRC Command Period"
set_parameter_property REF_COMMAND_PERIOD AFFECTS_GENERATION false
set_parameter_property REF_COMMAND_PERIOD HDL_PARAMETER true
add_parameter PRECH_COMMAND_PERIOD INTEGER 2 "tRP Command Period PRECHARGE TO ACTIVATE/REFRESH"
set_parameter_property PRECH_COMMAND_PERIOD DEFAULT_VALUE 2
set_parameter_property PRECH_COMMAND_PERIOD DISPLAY_NAME PRECH_COMMAND_PERIOD
set_parameter_property PRECH_COMMAND_PERIOD TYPE INTEGER
set_parameter_property PRECH_COMMAND_PERIOD UNITS None
set_parameter_property PRECH_COMMAND_PERIOD ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PRECH_COMMAND_PERIOD DESCRIPTION "tRP Command Period PRECHARGE TO ACTIVATE/REFRESH"
set_parameter_property PRECH_COMMAND_PERIOD AFFECTS_GENERATION false
set_parameter_property PRECH_COMMAND_PERIOD HDL_PARAMETER true
add_parameter ACT_TO_RW_CYCLES INTEGER 2 "tRCD Active Command To Read/Write Command Delay Time"
set_parameter_property ACT_TO_RW_CYCLES DEFAULT_VALUE 2
set_parameter_property ACT_TO_RW_CYCLES DISPLAY_NAME ACT_TO_RW_CYCLES
set_parameter_property ACT_TO_RW_CYCLES TYPE INTEGER
set_parameter_property ACT_TO_RW_CYCLES UNITS None
set_parameter_property ACT_TO_RW_CYCLES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ACT_TO_RW_CYCLES DESCRIPTION "tRCD Active Command To Read/Write Command Delay Time"
set_parameter_property ACT_TO_RW_CYCLES AFFECTS_GENERATION false
set_parameter_property ACT_TO_RW_CYCLES HDL_PARAMETER true
add_parameter IN_DATA_TO_PRE INTEGER 2 "tDPL Input Data To Precharge Command Delay"
set_parameter_property IN_DATA_TO_PRE DEFAULT_VALUE 2
set_parameter_property IN_DATA_TO_PRE DISPLAY_NAME IN_DATA_TO_PRE
set_parameter_property IN_DATA_TO_PRE TYPE INTEGER
set_parameter_property IN_DATA_TO_PRE UNITS None
set_parameter_property IN_DATA_TO_PRE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property IN_DATA_TO_PRE DESCRIPTION "tDPL Input Data To Precharge Command Delay"
set_parameter_property IN_DATA_TO_PRE AFFECTS_GENERATION false
set_parameter_property IN_DATA_TO_PRE HDL_PARAMETER true
add_parameter CAS_LAT_CYCLES INTEGER 2 "based on CAS Latency setting"
set_parameter_property CAS_LAT_CYCLES DEFAULT_VALUE 2
set_parameter_property CAS_LAT_CYCLES DISPLAY_NAME CAS_LAT_CYCLES
set_parameter_property CAS_LAT_CYCLES TYPE INTEGER
set_parameter_property CAS_LAT_CYCLES UNITS None
set_parameter_property CAS_LAT_CYCLES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CAS_LAT_CYCLES DESCRIPTION "Current implementation supports only 3"
set_parameter_property CAS_LAT_CYCLES AFFECTS_GENERATION false
set_parameter_property CAS_LAT_CYCLES HDL_PARAMETER true
add_parameter MODE_REG_CYCLES INTEGER 2 "tMRD (Mode Register Set To Command Delay Time 2 cycle)"
set_parameter_property MODE_REG_CYCLES DEFAULT_VALUE 2
set_parameter_property MODE_REG_CYCLES DISPLAY_NAME MODE_REG_CYCLES
set_parameter_property MODE_REG_CYCLES TYPE INTEGER
set_parameter_property MODE_REG_CYCLES UNITS None
set_parameter_property MODE_REG_CYCLES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MODE_REG_CYCLES DESCRIPTION "tMRD (Mode Register Set To Command Delay Time 2 cycle)"
set_parameter_property MODE_REG_CYCLES AFFECTS_GENERATION false
set_parameter_property MODE_REG_CYCLES HDL_PARAMETER true
add_parameter BURST_LENGTH INTEGER 0 "NOT USED! SEUD implementation requires a single access mode"
set_parameter_property BURST_LENGTH DEFAULT_VALUE 0
set_parameter_property BURST_LENGTH DISPLAY_NAME BURST_LENGTH
set_parameter_property BURST_LENGTH TYPE INTEGER
set_parameter_property BURST_LENGTH UNITS None
set_parameter_property BURST_LENGTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BURST_LENGTH DESCRIPTION "NOT USED! SEUD implementation requires a single access mode"
set_parameter_property BURST_LENGTH AFFECTS_GENERATION false
set_parameter_property BURST_LENGTH HDL_PARAMETER true
add_parameter RAM_COLS INTEGER 1024 ""
set_parameter_property RAM_COLS DEFAULT_VALUE 1024
set_parameter_property RAM_COLS DISPLAY_NAME RAM_COLS
set_parameter_property RAM_COLS TYPE INTEGER
set_parameter_property RAM_COLS UNITS None
set_parameter_property RAM_COLS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RAM_COLS DESCRIPTION ""
set_parameter_property RAM_COLS AFFECTS_GENERATION false
set_parameter_property RAM_COLS HDL_PARAMETER true
add_parameter RAM_ROWS INTEGER 8192
set_parameter_property RAM_ROWS DEFAULT_VALUE 8192
set_parameter_property RAM_ROWS DISPLAY_NAME RAM_ROWS
set_parameter_property RAM_ROWS TYPE INTEGER
set_parameter_property RAM_ROWS UNITS None
set_parameter_property RAM_ROWS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RAM_ROWS AFFECTS_GENERATION false
set_parameter_property RAM_ROWS HDL_PARAMETER true
add_parameter RAM_BANKS INTEGER 4
set_parameter_property RAM_BANKS DEFAULT_VALUE 4
set_parameter_property RAM_BANKS DISPLAY_NAME RAM_BANKS
set_parameter_property RAM_BANKS TYPE INTEGER
set_parameter_property RAM_BANKS UNITS None
set_parameter_property RAM_BANKS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RAM_BANKS AFFECTS_GENERATION false
set_parameter_property RAM_BANKS HDL_PARAMETER true
add_parameter TMR_COLS INTEGER 768
set_parameter_property TMR_COLS DEFAULT_VALUE 768
set_parameter_property TMR_COLS DISPLAY_NAME TMR_COLS
set_parameter_property TMR_COLS TYPE INTEGER
set_parameter_property TMR_COLS UNITS None
set_parameter_property TMR_COLS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property TMR_COLS AFFECTS_GENERATION false
set_parameter_property TMR_COLS HDL_PARAMETER true
add_parameter EXT_MODE_REG_EN BOOLEAN false "Enable only if the sdram supports an extended mode register set (EMRS)"
set_parameter_property EXT_MODE_REG_EN DEFAULT_VALUE false
set_parameter_property EXT_MODE_REG_EN DISPLAY_NAME EXT_MODE_REG_EN
set_parameter_property EXT_MODE_REG_EN TYPE BOOLEAN
set_parameter_property EXT_MODE_REG_EN UNITS None
set_parameter_property EXT_MODE_REG_EN DESCRIPTION "Enable only if the sdram supports an extended mode register set (EMRS)"
set_parameter_property EXT_MODE_REG_EN AFFECTS_GENERATION false
set_parameter_property EXT_MODE_REG_EN HDL_PARAMETER true
add_parameter GEN_ERR_INJ BOOLEAN TRUE "Enables the error injection unit. When in Space should be disabled to avoid any chance of error injection."
set_parameter_property GEN_ERR_INJ DEFAULT_VALUE false
set_parameter_property GEN_ERR_INJ DISPLAY_NAME GEN_ERR_INJ
set_parameter_property GEN_ERR_INJ TYPE BOOLEAN
set_parameter_property GEN_ERR_INJ UNITS None
set_parameter_property GEN_ERR_INJ DESCRIPTION "Enables the error injection unit. When in Space should be disabled to avoid any chance of error injection."
set_parameter_property GEN_ERR_INJ AFFECTS_GENERATION TRUE
set_parameter_property GEN_ERR_INJ HDL_PARAMETER true
add_parameter SCRUBBER_WAIT_CYCLES INTEGER 339
set_parameter_property SCRUBBER_WAIT_CYCLES DEFAULT_VALUE 8
set_parameter_property SCRUBBER_WAIT_CYCLES DISPLAY_NAME SCRUBBER_WAIT_CYCLES
set_parameter_property SCRUBBER_WAIT_CYCLES TYPE INTEGER
set_parameter_property SCRUBBER_WAIT_CYCLES UNITS None
set_parameter_property SCRUBBER_WAIT_CYCLES ALLOWED_RANGES 2:2147483647
set_parameter_property SCRUBBER_WAIT_CYCLES DESCRIPTION "Controls the scrubbing rate by delaying the scrubbing set cycles"
set_parameter_property SCRUBBER_WAIT_CYCLES AFFECTS_GENERATION false
set_parameter_property SCRUBBER_WAIT_CYCLES HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point seud_sdram_ctrl
# | 
add_interface seud_sdram_ctrl avalon end
set_interface_property seud_sdram_ctrl addressAlignment NATIVE
set_interface_property seud_sdram_ctrl associatedClock clock_interface
set_interface_property seud_sdram_ctrl burstOnBurstBoundariesOnly false
set_interface_property seud_sdram_ctrl explicitAddressSpan 33554436
set_interface_property seud_sdram_ctrl holdTime 0
set_interface_property seud_sdram_ctrl isMemoryDevice true
set_interface_property seud_sdram_ctrl isNonVolatileStorage false
set_interface_property seud_sdram_ctrl linewrapBursts false
set_interface_property seud_sdram_ctrl maximumPendingReadTransactions 0
set_interface_property seud_sdram_ctrl printableDevice false
set_interface_property seud_sdram_ctrl readLatency 0
set_interface_property seud_sdram_ctrl readWaitStates 0
set_interface_property seud_sdram_ctrl readWaitTime 0
set_interface_property seud_sdram_ctrl setupTime 0
set_interface_property seud_sdram_ctrl timingUnits Cycles
set_interface_property seud_sdram_ctrl writeWaitTime 0

set_interface_property seud_sdram_ctrl ASSOCIATED_CLOCK clock_interface
set_interface_property seud_sdram_ctrl ENABLED true

add_interface_port seud_sdram_ctrl avs_read read Input 1
add_interface_port seud_sdram_ctrl avs_readdata readdata Output data_width
add_interface_port seud_sdram_ctrl avs_write write Input 1
add_interface_port seud_sdram_ctrl avs_writedata writedata Input data_width
add_interface_port seud_sdram_ctrl avs_address address Input COLS_WIDTH+ROW_WIDTH+BANK_WIDTH+1
add_interface_port seud_sdram_ctrl avs_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_interface
# | 
add_interface clock_interface clock end

set_interface_property clock_interface ENABLED true

add_interface_port clock_interface csi_clock clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_interface
# | 
add_interface reset_interface reset end
set_interface_property reset_interface associatedClock clock_interface
set_interface_property reset_interface synchronousEdges DEASSERT

set_interface_property reset_interface ASSOCIATED_CLOCK clock_interface
set_interface_property reset_interface ENABLED true

add_interface_port reset_interface rsi_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point DRAM_CLK
# | 
add_interface DRAM_CLK conduit end

set_interface_property DRAM_CLK ENABLED true

add_interface_port DRAM_CLK clk_o export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point DRAM_CKE
# | 
add_interface DRAM_CKE conduit end

set_interface_property DRAM_CKE ENABLED true

add_interface_port DRAM_CKE cke_o export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point DRAM_BANK
# | 
add_interface DRAM_BANK conduit end

set_interface_property DRAM_BANK ENABLED true

add_interface_port DRAM_BANK bank_o export Output bank_width
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point DRAM_ADDR
# | 
add_interface DRAM_ADDR conduit end

set_interface_property DRAM_ADDR ENABLED true

add_interface_port DRAM_ADDR addr_o export Output row_width
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point DRAM_CS
# | 
add_interface DRAM_CS conduit end

set_interface_property DRAM_CS ENABLED true

add_interface_port DRAM_CS cs_o export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point DRAM_RAS
# | 
add_interface DRAM_RAS conduit end

set_interface_property DRAM_RAS ENABLED true

add_interface_port DRAM_RAS ras_o export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point DRAM_CAS
# | 
add_interface DRAM_CAS conduit end

set_interface_property DRAM_CAS ENABLED true

add_interface_port DRAM_CAS cas_o export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point DRAM_WE
# | 
add_interface DRAM_WE conduit end

set_interface_property DRAM_WE ENABLED true

add_interface_port DRAM_WE we_o export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point DRAM_DQM
# | 
add_interface DRAM_DQM conduit end

set_interface_property DRAM_DQM ENABLED true

add_interface_port DRAM_DQM dqm_o export Output dqm_width
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point DRAM_DATAQ
# | 
add_interface DRAM_DATAQ conduit end

set_interface_property DRAM_DATAQ ENABLED true

add_interface_port DRAM_DATAQ dataQ_io export Bidir data_width
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ERR_DETECT
# | 
add_interface ERR_DETECT conduit end

set_interface_property ERR_DETECT ENABLED true

add_interface_port ERR_DETECT err_detect_o export Output 1
add_interface_port ERR_DETECT err_counter_o export Output data_width
add_interface_port ERR_DETECT voted_data_o export Output data_width
add_interface_port ERR_DETECT scrubbing_proc_run_o export Output 1
add_interface_port ERR_DETECT healing_proc_run_o export Output 1
# | 
# +-----------------------------------
