# TCL File Generated by Component Editor 16.1
# Thu Jul 20 15:00:31 EEST 2017
# DO NOT MODIFY


# 
# sevensegment_avalon_master_interface "Sevensegment Avalon-MM Master Display" v1.0
# Eleftherios Kyriakakis 2017.07.20.15:00:31
# Reads out a specified address from an avalon slave and displays it
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module sevensegment_avalon_master_interface
# 
set_module_property DESCRIPTION "Reads out a specified address from an avalon slave and displays it"
set_module_property NAME sevensegment_avalon_master_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Peripherals
set_module_property AUTHOR "Eleftherios Kyriakakis"
set_module_property DISPLAY_NAME "Sevensegment Avalon-MM Master Display"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sevensegment_avalon_master_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sevensegmentdecoder.vhd VHDL PATH ../other_src/sevensegmentdecoder.vhd
add_fileset_file sevensegment_avalon_master_interface.vhd VHDL PATH ../other_src/sevensegment_avalon_master_interface.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ADDRESS_WIDTH INTEGER 25
set_parameter_property ADDRESS_WIDTH DEFAULT_VALUE 25
set_parameter_property ADDRESS_WIDTH DISPLAY_NAME ADDRESS_WIDTH
set_parameter_property ADDRESS_WIDTH TYPE INTEGER
set_parameter_property ADDRESS_WIDTH UNITS None
set_parameter_property ADDRESS_WIDTH HDL_PARAMETER true
add_parameter UPDATE_RATE INTEGER 128
set_parameter_property UPDATE_RATE DEFAULT_VALUE 128
set_parameter_property UPDATE_RATE DISPLAY_NAME UPDATE_RATE
set_parameter_property UPDATE_RATE TYPE INTEGER
set_parameter_property UPDATE_RATE UNITS None
set_parameter_property UPDATE_RATE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_master_0
# 
add_interface avalon_master_0 avalon start
set_interface_property avalon_master_0 addressUnits SYMBOLS
set_interface_property avalon_master_0 associatedClock clock
set_interface_property avalon_master_0 associatedReset reset
set_interface_property avalon_master_0 bitsPerSymbol 8
set_interface_property avalon_master_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_master_0 burstcountUnits WORDS
set_interface_property avalon_master_0 doStreamReads false
set_interface_property avalon_master_0 doStreamWrites false
set_interface_property avalon_master_0 holdTime 0
set_interface_property avalon_master_0 linewrapBursts false
set_interface_property avalon_master_0 maximumPendingReadTransactions 0
set_interface_property avalon_master_0 maximumPendingWriteTransactions 0
set_interface_property avalon_master_0 readLatency 0
set_interface_property avalon_master_0 readWaitTime 1
set_interface_property avalon_master_0 setupTime 0
set_interface_property avalon_master_0 timingUnits Cycles
set_interface_property avalon_master_0 writeWaitTime 0
set_interface_property avalon_master_0 ENABLED true
set_interface_property avalon_master_0 EXPORT_OF ""
set_interface_property avalon_master_0 PORT_NAME_MAP ""
set_interface_property avalon_master_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_0 avm_address address Output address_width
add_interface_port avalon_master_0 avm_read read Output 1
add_interface_port avalon_master_0 avm_readdata readdata Input data_width
add_interface_port avalon_master_0 avm_write write Output 1
add_interface_port avalon_master_0 avm_writedata writedata Output data_width
add_interface_port avalon_master_0 avm_waitrequest waitrequest Input 1
add_interface_port avalon_master_0 avm_readdatavalid readdatavalid Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1


# 
# connection point sevenseg_conduit
# 
add_interface sevenseg_conduit conduit end
set_interface_property sevenseg_conduit associatedClock ""
set_interface_property sevenseg_conduit associatedReset ""
set_interface_property sevenseg_conduit ENABLED true
set_interface_property sevenseg_conduit EXPORT_OF ""
set_interface_property sevenseg_conduit PORT_NAME_MAP ""
set_interface_property sevenseg_conduit CMSIS_SVD_VARIABLES ""
set_interface_property sevenseg_conduit SVD_ADDRESS_GROUP ""

add_interface_port sevenseg_conduit HEX7 hex7 Output 7
add_interface_port sevenseg_conduit HEX6 hex6 Output 7
add_interface_port sevenseg_conduit HEX5 hex5 Output 7
add_interface_port sevenseg_conduit HEX4 hex4 Output 7
add_interface_port sevenseg_conduit HEX3 hex3 Output 7
add_interface_port sevenseg_conduit HEX2 hex2 Output 7
add_interface_port sevenseg_conduit HEX1 hex1 Output 7
add_interface_port sevenseg_conduit HEX0 hex0 Output 7


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clock clk Input 1

