# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/egk69/Documents/Development/EDAC_SDRAM_Controller/Xilinx/artix_sdram_demo/artix_sdram_demo.srcs/sources_1/bd/DemoSDRAM/ip/DemoSDRAM_axi_traffic_gen_0_0/DemoSDRAM_axi_traffic_gen_0_0.xci
# IP: The module: 'DemoSDRAM_axi_traffic_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/egk69/Documents/Development/EDAC_SDRAM_Controller/Xilinx/artix_sdram_demo/artix_sdram_demo.srcs/sources_1/bd/DemoSDRAM/ip/DemoSDRAM_axi_traffic_gen_0_0/DemoSDRAM_axi_traffic_gen_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoSDRAM_axi_traffic_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/egk69/Documents/Development/EDAC_SDRAM_Controller/Xilinx/artix_sdram_demo/artix_sdram_demo.srcs/sources_1/bd/DemoSDRAM/ip/DemoSDRAM_axi_traffic_gen_0_0/DemoSDRAM_axi_traffic_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoSDRAM_axi_traffic_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/egk69/Documents/Development/EDAC_SDRAM_Controller/Xilinx/artix_sdram_demo/artix_sdram_demo.srcs/sources_1/bd/DemoSDRAM/ip/DemoSDRAM_axi_traffic_gen_0_0/DemoSDRAM_axi_traffic_gen_0_0.xci
# IP: The module: 'DemoSDRAM_axi_traffic_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/egk69/Documents/Development/EDAC_SDRAM_Controller/Xilinx/artix_sdram_demo/artix_sdram_demo.srcs/sources_1/bd/DemoSDRAM/ip/DemoSDRAM_axi_traffic_gen_0_0/DemoSDRAM_axi_traffic_gen_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoSDRAM_axi_traffic_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/egk69/Documents/Development/EDAC_SDRAM_Controller/Xilinx/artix_sdram_demo/artix_sdram_demo.srcs/sources_1/bd/DemoSDRAM/ip/DemoSDRAM_axi_traffic_gen_0_0/DemoSDRAM_axi_traffic_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoSDRAM_axi_traffic_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
