create_clock -period 83.333 -name sys_clk_pin -waveform {0.000 41.667} -add [get_ports clk_shared]

set_property -dict {PACKAGE_PIN D6 IOSTANDARD LVCMOS18} [get_ports cke_o]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS18} [get_ports ras_o]
set_property -dict {PACKAGE_PIN G5 IOSTANDARD LVCMOS18} [get_ports {bank_o[0]}]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS18} [get_ports {bank_o[1]}]
set_property -dict {PACKAGE_PIN F5 IOSTANDARD LVCMOS18} [get_ports {addr_o[3]}]
set_property -dict {PACKAGE_PIN E5 IOSTANDARD LVCMOS18} [get_ports {addr_o[0]}]
set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS18} [get_ports we_o]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS18} [get_ports sdram_clk]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS18} [get_ports {addr_o[4]}]
set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[3]}]
set_property -dict {PACKAGE_PIN B5 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[0]}]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[2]}]
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[1]}]
set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS18} [get_ports {addr_o[1]}]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS18} [get_ports {addr_o[2]}]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[7]}]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[6]}]
set_property -dict {PACKAGE_PIN A2 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[5]}]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[4]}]
set_property -dict {PACKAGE_PIN A22 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[8]}]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[9]}]
set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[10]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS18} [get_ports {addr_o[9]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[13]}]
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[14]}]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[11]}]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[12]}]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS18} [get_ports {addr_o[6]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS18} [get_ports {dqm_o[1]}]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS18} [get_ports {addr_o[12]}]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS18} [get_ports {addr_o[8]}]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS18} [get_ports {addr_o[7]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS18} [get_ports {addr_o[5]}]
set_property -dict {PACKAGE_PIN C3 IOSTANDARD LVCMOS18} [get_ports {addr_o[10]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS18} [get_ports {dqm_o[0]}]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS18} [get_ports {dataQ_io[15]}]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVCMOS18} [get_ports {addr_o[11]}]
set_property -dict {PACKAGE_PIN AE2 IOSTANDARD LVCMOS18} [get_ports status_led]
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS18} [get_ports clk_shared]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS18} [get_ports cs_o]
set_property PACKAGE_PIN E6 [get_ports cas_o]
set_property IOSTANDARD LVCMOS18 [get_ports cas_o]

set_property PULLUP true [get_ports cas_o]
set_property PULLUP true [get_ports cs_o]
set_property PULLUP true [get_ports we_o]
set_property PULLUP true [get_ports ras_o]
set_property PULLUP true [get_ports cke_o]
#set_property PULLDOWN true [get_ports {dataQ_io[0]}]
#set_property PULLDOWN true [get_ports {dataQ_io[1]}]
#set_property PULLDOWN true [get_ports {dataQ_io[2]}]
#set_property PULLDOWN true [get_ports {dataQ_io[3]}]
#set_property PULLDOWN true [get_ports {dataQ_io[4]}]
#set_property PULLDOWN true [get_ports {dataQ_io[5]}]
#set_property PULLDOWN true [get_ports {dataQ_io[6]}]
#set_property PULLDOWN true [get_ports {dataQ_io[7]}]
#set_property PULLDOWN true [get_ports {dataQ_io[8]}]
#set_property PULLDOWN true [get_ports {dataQ_io[9]}]
#set_property PULLDOWN true [get_ports {dataQ_io[10]}]
#set_property PULLDOWN true [get_ports {dataQ_io[11]}]
#set_property PULLDOWN true [get_ports {dataQ_io[12]}]
#set_property PULLDOWN true [get_ports {dataQ_io[13]}]
#set_property PULLDOWN true [get_ports {dataQ_io[14]}]
#set_property PULLDOWN true [get_ports {dataQ_io[15]}]
#set_property PULLDOWN true [get_ports {dqm_o[0]}]
#set_property PULLDOWN true [get_ports {dqm_o[1]}]
set_property PULLDOWN true [get_ports status_led]

set_property SLEW FAST [get_ports status_led]

#set_property PULLDOWN true [get_ports sdram_clk]
#set_property PULLDOWN true [get_ports cke_o]
#set_property PULLDOWN true [get_ports {addr_o[0]}]
#set_property PULLDOWN true [get_ports {addr_o[1]}]
#set_property PULLDOWN true [get_ports {addr_o[2]}]
#set_property PULLDOWN true [get_ports {addr_o[3]}]
#set_property PULLDOWN true [get_ports {addr_o[4]}]
#set_property PULLDOWN true [get_ports {addr_o[5]}]
#set_property PULLDOWN true [get_ports {addr_o[6]}]
#set_property PULLDOWN true [get_ports {addr_o[7]}]
#set_property PULLDOWN true [get_ports {addr_o[8]}]
#set_property PULLDOWN true [get_ports {addr_o[9]}]
#set_property PULLDOWN true [get_ports {addr_o[10]}]
#set_property PULLDOWN true [get_ports {addr_o[11]}]
#set_property PULLDOWN true [get_ports {addr_o[12]}]
#set_property PULLDOWN true [get_ports {bank_o[0]}]
#set_property PULLDOWN true [get_ports {bank_o[1]}]
#set_property PULLDOWN true [get_ports clk_shared]

create_property iob port -type string
set_property IOB TRUE [all_inputs]
set_property IOB TRUE [all_outputs]